CREATE TABLE [dbo].[CashTransferMemo] (
    [MemoId]             VARCHAR (50)    NULL,
    [MemoNo]             INT             NULL,
    [MemoDate]           DATETIME        NULL,
    [MemoType]           VARCHAR (50)    NULL,
    [Amount]             DECIMAL (18, 2) NULL,
    [Denom2000]          INT             NULL,
    [Denom500]           INT             NULL,
    [Denom200]           INT             NULL,
    [Denom100]           INT             NULL,
    [Denom50]            INT             NULL,
    [Denom20]            INT             NULL,
    [Denom10]            INT             NULL,
    [Denom5]             INT             NULL,
    [Denom2]             INT             NULL,
    [Denom1]             INT             NULL,
    [FromCash]           VARCHAR (50)    NULL,
    [ToCash]             VARCHAR (50)    NULL,
    [FromLoc]            VARCHAR (50)    NULL,
    [ToLoc]              VARCHAR (50)    NULL,
    [Remarks]            NVARCHAR (MAX)  NULL,
    [CreatedOn]          DATETIME        NULL,
    [CreatedBy]          VARCHAR (50)    NULL,
    [Status]             TINYINT         NULL,
    [BankId]             VARCHAR (50)    NULL,
    [MemoNoToDisplay]    NVARCHAR (50)   NULL,
    [ShiftId]            VARCHAR (50)    NULL,
    [ShiftIdToDisplay]   NVARCHAR (50)   NULL,
    [SessionIdToDisplay] NVARCHAR (50)   NULL,
    [EntrySource]        VARCHAR (20)    NULL,
    [SyncStatus]         INT             NULL,
    [SyncAction]         VARCHAR (10)    NULL
);

