CREATE TABLE [dbo].[Location_Master] (
    [locationID]         VARCHAR (50)   NOT NULL,
    [LocationName]       NVARCHAR (50)  NOT NULL,
    [CreatUnder]         NVARCHAR (50)  NULL,
    [LocDecp]            NVARCHAR (200) NOT NULL,
    [L_Address]          NVARCHAR (600) NULL,
    [L_City]             NVARCHAR (50)  NULL,
    [L_District]         NVARCHAR (50)  NULL,
    [L_State]            NVARCHAR (50)  NULL,
    [LocationClass]      NVARCHAR (50)  NULL,
    [InventoryValuation] BIT            NULL,
    [Loc_Type]           VARCHAR (50)   NULL,
    [GrinTrack]          BIT            NULL,
    [L_Zip]              VARCHAR (50)   NULL,
    [IsBranch]           BIT            NULL,
    [ContactPerson]      VARCHAR (50)   NULL,
    [Phone]              VARCHAR (50)   NULL,
    [Email]              VARCHAR (50)   NULL,
    [TinNo]              VARCHAR (50)   NULL,
    [TinRegDate]         DATETIME       NULL,
    [CSTNo]              VARCHAR (50)   NULL,
    [CSTRegDate]         DATETIME       NULL,
    [CustomCircle]       VARCHAR (100)  NULL,
    [IsCircle]           BIT            NULL,
    [ShortName]          VARCHAR (50)   NULL,
    [Declaration]        VARCHAR (MAX)  NULL,
    [IsCSA]              BIT            NULL,
    [PAN_No]             VARCHAR (50)   NULL,
    [ECC_Code]           VARCHAR (50)   NULL,
    [IECC_Code]          VARCHAR (50)   NULL,
    [NECC_Code]          VARCHAR (50)   NULL,
    [Location_Code]      VARCHAR (50)   NULL,
    [Range]              VARCHAR (50)   NULL,
    [Division]           VARCHAR (50)   NULL,
    [Comm_Rate]          VARCHAR (50)   NULL,
    [loc_Code]           VARCHAR (50)   NULL,
    [GSTNo]              VARCHAR (50)   NULL,
    [Loc_Status]         BIT            NULL,
    [LLP_No]             VARCHAR (50)   NULL,
    [IsCurrentLocation]  INT            NULL,
    CONSTRAINT [PK_Location_Master] PRIMARY KEY CLUSTERED ([locationID] ASC)
);

